# apps/coco/Dockerfile.dev

# Use the official Node.js image as a base image
FROM node:16

RUN apt-get update && apt-get install -y build-essential python3
# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package.json ./

# Install the dependencies
RUN npm install ci

# Copy the entire nx monorepo to the container
COPY . .

# Declare arguments and set them as environment variables
ARG PORT

ENV PORT=$PORT

# Expose the API port
EXPOSE $PORT

# Start the development server
CMD ["npx", "nx", "serve", "coco", "--host 0.0.0.0"]

