# apps/coco-fe/Dockerfile.dev

# Use the official Node.js image as a base image
FROM node:16

RUN apt-get update && apt-get install -y build-essential python3

# Set the working directory in the container
WORKDIR /app

ARG API_URL
ENV API_URL=$API_URL
ENV NODE_ENV=$NODE_ENV

# Copy package.json and package-lock.json to the container
COPY package*.json ./
COPY decorate-angular-cli.js ./

# Install the dependencies
RUN npm install --verbose
RUN npm i -g @nrwl/nx-linux-arm64-gnu
# Copy the entire nx monorepo to the container
COPY . .



# Run the set-api-url.js script
RUN ls && API_URL=$API_URL NODE_ENV=$NODE_ENV node ./tools/setup-api-url.js
RUN ls tools
# Expose the frontend port
EXPOSE 4200

# Start the development server
CMD ["npx", "nx", "serve", "coco-fe","--configuration","development", "--host", "0.0.0.0"]

